### ISSUE TITLE
Error in line 125 of noaa.py running sample

### ISSUE THREAD

**Issue by slowtoaccept** [paulokuong/noaa#20]
C:\Users\Jerry\Python_Projects\Noaa-SDK
(Noaa-SDK) λ python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from noaa_sdk import noaa
>>> n = noaa.NOAA
>>> res = n.get_forecasts('06405', 'US', True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jerry\Python_Projects\Noaa-SDK\lib\site-packages\noaa_sdk\noaa.py", line 125, in get_forecasts
    lat, lon = self._osm.get_lat_lon_by_postalcode_country(
AttributeError: 'str' object has no attribute '_osm'
>>>

**Comment by pkuong** [comment]
@slowtoaccept you are missing bracket when you instantiate the class:

<img width="680" alt="Screen Shot 2020-10-04 at 5 57 49 PM" src="https://user-images.githubusercontent.com/1965806/95028027-2f506f80-066b-11eb-9862-a8fe7c8e3e1e.png">

**Comment by paulokuong** [comment]
seems not an issue, closing
