### ISSUE TITLE
API calls always sleep for a couple of seconds before returning

### ISSUE THREAD

**Issue by moredip** [paulokuong/noaa#27]
As far as I can tell, there's a bug in the retry logic in `UTIL._get` which means that any API call using that helper method will always sleep for two second before returning.

https://github.com/paulokuong/noaa/blob/e34786e6fce1e0301d8f69b383ca1ba656e8d19d/noaa_sdk/util.py#L56

The method has retry logic in it which includes a sleep before retrying. However, as currently implemented it appears to sleep even if the first attempt is successful, because even the first pass through the while statement ends up calling `time.sleep` with a value of 2.

I *think* one way to resolve this would be to initialize new_interval to 0 before entering that while loop, and then doing the `time.sleep(new_interval)` call before the `new_interval = fib_num_b + fib_num_a` assignment.

**Comment by paulokuong** [comment]
fixed this in release 0.1.21
