### ISSUE TITLE
Pinned `requests` version

### ISSUE THREAD

**Issue by kevinamstutz** [paulokuong/noaa#28]
The `setup.py` indicates `requests>=2.22.0`, however, if I run the following:

```bash
curl -sL https://pypi.org/pypi/noaa-sdk/json | jq '.info.requires_dist'
```

I get:

```
[
  "requests (==2.22.0)"
]
```

This is causing dependency conflicts with a variety of packages that require a newer version of `requests`. Would it be possible to update the metadata on pypi to reflect the versioning shown in your `setup.py`? Thank you!

**Comment by jeking3** [comment]
It has been fixed on master, so @paulokuong just needs to roll a new release.  In the meantime you can pin your download to a git hash from the repo.  (See: https://github.com/paulokuong/noaa/commit/e34786e6fce1e0301d8f69b383ca1ba656e8d19d)

**Comment by paulokuong** [comment]
Fixed.
