### ISSUE TITLE
Forecasts and observations without geocode lookup?

### ISSUE THREAD

**Issue by hawkeye217** [paulokuong/noaa#3]
Would it be possible for you to write or modify your `get_forecasts()` and `get_observations()` functions to take points as arguments rather than postal code/country?  I'm looking at writing a custom component for Home Assistant where the latitude/longitude is already available and the OSM lookup would be redundant.

Thanks for considering!

**Comment by meichthys** [comment]
+1 for the homeassistant component! I don't think it would be too difficult to use lat/lon since the underlying NOAA api uses those anyway. I'll take a look if i get a chance.

**Comment by meichthys** [comment]
@hawkeye217  It looks like this is already implemented. You should be able to use the `points_forecast` method.

**Comment by hawkeye217** [comment]
I ended up writing a custom component for Home Assistant (based off the code in the WUnderground component) that fetches the forecast based on the latitude/logitude in the HA config. 

I may clean it up at some point and throw it on Github.  Wasn't all that hard to put together.
