### ISSUE TITLE
Python 2 Compatibility

### ISSUE THREAD

**Issue by kevroy314** [paulokuong/noaa#5]
Great package! I made it python 2 compatible with just 2 minor changes in case you'd like to include that. You can find my fork here: https://github.com/kevroy314/noaa

Basically just need to swap
`from urllib.parse import urlparse`

for

`
try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse
`

add `future` to `requirements.txt`

and add `from future.builtins import super` to the tops of the two files that call `super`.

**Comment by paulokuong** [comment]
@kevroy314 sorry, but there will be just 6 months before the maintenance of python 2 stops. Check out this clock: https://pythonclock.org/
duck and cover for the doomsday...

**Comment by kevroy314** [comment]
Totally understand - there are some packages which, unfortunately, still don't support python 3. I was stuck using such a package and didn't have the ability to upgrade it, so getting things to work backwards was my only option.
